# -*- coding: utf-8 -*-
"""Bienvenue dans Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

pip install ucimlrepo

from ucimlrepo import fetch_ucirepo

# fetch dataset
regensburg_pediatric_appendicitis = fetch_ucirepo(id=938)

# data (as pandas dataframes)
X = regensburg_pediatric_appendicitis.data.features
y = regensburg_pediatric_appendicitis.data.targets

# metadata
print(regensburg_pediatric_appendicitis.metadata)

# variable information
print(regensburg_pediatric_appendicitis.variables)

# ============================================
# ANALYSE DU DATASET "Regensburg Pediatric Appendicitis"
# ============================================

# 1. Import des librairies
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from ucimlrepo import fetch_ucirepo

# 2. Chargement du dataset
dataset = fetch_ucirepo(id=938)
X = dataset.data.features
y = dataset.data.targets
data = pd.concat([X, y], axis=1)

# 3. Aperçu du dataset
print("Dimensions du dataset :", data.shape)
display(data.head())
data.info()
display(data.describe(include='all'))

# 4. Vérification des valeurs manquantes
print("Valeurs manquantes par colonne :")
display(data.isnull().sum())

# 5. Analyse de la variable cible
target_col = y.columns[0]
print(f"Distribution de la variable cible '{target_col}' :")
display(y[target_col].value_counts())

plt.figure(figsize=(5,4))
sns.countplot(x=target_col, data=y, palette="viridis")
plt.title("Distribution de la variable cible")
plt.show()

# 6. Distribution des variables numériques
num_cols = X.select_dtypes(include=np.number).columns
X[num_cols].hist(figsize=(15,10), bins=15, color='skyblue', edgecolor='black')
plt.suptitle("Distribution des variables numériques")
plt.show()

# 7. Matrice de corrélation
plt.figure(figsize=(10,8))
sns.heatmap(X[num_cols].corr(), annot=True, fmt=".2f", cmap="coolwarm")
plt.title("Corrélation des variables numériques")
plt.show()

# 8. Analyse bivariée avec la cible (top 5 variables numériques)
for col in num_cols[:5]:
    plt.figure(figsize=(6,4))
    sns.boxplot(x=y[target_col], y=X[col], palette="Set2")
    plt.title(f"{col} vs {target_col}")
    plt.show()

# 9. Analyse des variables catégorielles
cat_cols = X.select_dtypes(exclude=np.number).columns
for col in cat_cols:
    plt.figure(figsize=(6,4))
    sns.countplot(x=col, hue=target_col, data=data, palette="pastel")
    plt.title(f"{col} selon la variable cible")
    plt.xticks(rotation=45)
    plt.show()

# 10. Résumé
print("Analyse exploratoire terminée.")
print(f"- Variables numériques : {len(num_cols)}")
print(f"- Variables catégorielles : {len(cat_cols)}")
print(f"- Variable cible : {target_col}")